apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name     : prometheus-blackbox-exporter
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name     : in-cluster
    namespace: grafana-loki
  sources:
    - chart: prometheus-blackbox-exporter
      repoURL: https://prometheus-community.github.io/helm-charts
      targetRevision: 11.*
      helm:
        releaseName: prometheus-blackbox-exporter
        passCredentials: false
        valueFiles:
          - $my-configs/charts/grafana-loki/dev/blackbox-exporter_values_dev.yaml
          
    - repoURL: "https://github.com/YURIIOZHHO/argocd-loki"
      targetRevision: main
      ref: my-configs

  project: default
  syncPolicy:
    automated:
      prune   : true
      selfHeal: true
