apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: psmdb-mongodb
  namespace: argocd
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUpdate: 1
  generators:
    - list:
        elements:
          - name: psmdb-01-crds
            repoURL: https://percona.github.io/percona-helm-charts/
            chart: psmdb-operator-crds
            targetRevision: 1.22.0
          - name: psmdb-02-operator
            repoURL: https://percona.github.io/percona-helm-charts/
            chart: psmdb-operator
            targetRevision: 1.22.0
          - name: psmdb-03-instance
            repoURL: "https://github.com/YURIIOZHHO/argocd-test.git"
            path: "charts/mongodb-eks/dev"
            targetRevision: main
  template:
    metadata:
      name: '{{name}}'
    spec:
      project: default
      source:
        repoURL: '{{repoURL}}'
        chart: '{{chart}}'
        path: '{{path}}'   
        targetRevision: '{{targetRevision}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: mongodb-eks
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
          - SkipDryRunOnMissingResource=true